server:
  port: 8702

spring:
  application:
    name: authorization

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: test

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8701/eureka/

jwt:
  sign:
    key: "123"