spring:
  application:
    name: gateway

server:
  port: 8700

zuul:
  routes:
    auth:
      path: '/auth/**'
      sensitiveHeaders:
      serviceId: authorization
    service1:
      path: '/service/**'
      sensitiveHeaders:
      serviceId: service
  prefix: "/api"

eureka:
  client:
    serviceUrl:
      defaultZone: http://discoveryserver:8701/eureka/
    enabled: true
    register-with-eureka: true
    fetch-registry: true

ribbon:
  ConnectTimeout:  10000
  ReadTimeout:  10000
  eager-load:
    enabled: true

hystrix:
  command:
    execution:
      timeout:
        enabled: false
      isolation:
        strategy: THREAD
        thread:
          timeoutInMilliseconds: 6000